"""empty message

Revision ID: e64a0b7fbbf7
Revises: e544b1cd1dbb
Create Date: 2024-06-17 15:05:56.436196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64a0b7fbbf7'
down_revision = 'e544b1cd1dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_items_table_set_id_set_table'), 'set_table', ['set_id'], ['id'])

    with op.batch_alter_table('set_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_set_table_item_id_items_table', type_='foreignkey')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_set_table_item_id_items_table', 'items_table', ['item_id'], ['id'])

    with op.batch_alter_table('items_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_items_table_set_id_set_table'), type_='foreignkey')
        batch_op.drop_column('set_id')

    # ### end Alembic commands ###
